# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modelserver.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11modelserver.proto\x12\x0bmodelserver\" \n\x0fSetCoefsRequest\x12\r\n\x05\x63oefs\x18\x01 \x03(\x02\"!\n\x10SetCoefsResponse\x12\r\n\x05\x65rror\x18\x01 \x01(\t\"\x1b\n\x0ePredictRequest\x12\t\n\x01X\x18\x01 \x03(\x02\"8\n\x0fPredictResponse\x12\t\n\x01y\x18\x01 \x01(\x02\x12\x0b\n\x03hit\x18\x02 \x01(\x08\x12\r\n\x05\x65rror\x18\x03 \x01(\t2\x9c\x01\n\x0bModelServer\x12G\n\x08SetCoefs\x12\x1c.modelserver.SetCoefsRequest\x1a\x1d.modelserver.SetCoefsResponse\x12\x44\n\x07Predict\x12\x1b.modelserver.PredictRequest\x1a\x1c.modelserver.PredictResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'modelserver_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SETCOEFSREQUEST']._serialized_start=34
  _globals['_SETCOEFSREQUEST']._serialized_end=66
  _globals['_SETCOEFSRESPONSE']._serialized_start=68
  _globals['_SETCOEFSRESPONSE']._serialized_end=101
  _globals['_PREDICTREQUEST']._serialized_start=103
  _globals['_PREDICTREQUEST']._serialized_end=130
  _globals['_PREDICTRESPONSE']._serialized_start=132
  _globals['_PREDICTRESPONSE']._serialized_end=188
  _globals['_MODELSERVER']._serialized_start=191
  _globals['_MODELSERVER']._serialized_end=347
# @@protoc_insertion_point(module_scope)
